sudo: required
services:
  - docker
language: java
before_install:
  - pip install --user codecov
after_success:
  - mvn clean compile cobertura:cobertura coveralls:report install
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
  docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
  docker push sidlors/ajax4jsf-demo;
  fi
jdk:
- oraclejdk8
