sudo: required
services:
  - docker
language: java
after_success:
  - mvn clean compile install
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
  docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
  docker push sidlors/ajax4jsf-demo;
  fi
jdk:
- oraclejdk8
